apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - name: kube-state-metrics
        imagePullPolicy: IfNotPresent
        image: gcr.io/google_containers/kube-state-metrics:v1.0.1
        ports:
        - containerPort: 8080
