apiVersion: v1
kind: Service
metadata:
  name: demo-app-success
  labels:
    app: demo-app
    project: cncf
    version: "1"
spec:
  selector:
    app: demo-app
    project: cncf
    version: "1"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-fail
  labels:
    app: demo-app
    project: cncf
    version: "2"
spec:
  selector:
    app: demo-app
    project: cncf
    version: "2"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: demo-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: demo-app
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: demo-app-success
  labels:
    app: demo-app
    project: cncf
    version: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      project: cncf
      version: "1"
  template:
    metadata:
      labels:
        app: demo-app
        project: cncf
        version: "1"
      annotations:
        service-discovery.datadoghq.com/demo-app.check_names: '["go_expvar"]'
        service-discovery.datadoghq.com/demo-app.init_configs: '[{}]'
        service-discovery.datadoghq.com/demo-app.instances: '[{"expvar_url": "http://%%host%%:8080", "metrics": [{"path": "demo.requests.failures", "type": "counter"}, {"path": "demo.requests.success", "type": "counter"}]}]'
    spec:
      containers:
      - name: demo-app
        image: hkaj/demo-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: demo-app-fail
  labels:
    app: demo-app
    project: cncf
    version: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      project: cncf
      version: "2"
  template:
    metadata:
      labels:
        app: demo-app
        project: cncf
        version: "2"
      annotations:
        service-discovery.datadoghq.com/demo-app.check_names: '["go_expvar"]'
        service-discovery.datadoghq.com/demo-app.init_configs: '[{}]'
        service-discovery.datadoghq.com/demo-app.instances: '[{"expvar_url": "http://%%host%%:8080", "metrics": [{"path": "demo.requests.failures", "type": "counter"}, {"path": "demo.requests.success", "type": "counter"}]}]'
    spec:
      containers:
      - name: demo-app
        image: hkaj/demo-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
