apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    project: cncf
spec:
  type: LoadBalancer
  selector:
    app: nginx
    project: cncf
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    project: cncf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      project: cncf
  template:
    metadata:
      labels:
        app: nginx
        project: cncf
      annotations:
        service-discovery.datadoghq.com/nginx.check_names: '["nginx"]'
        service-discovery.datadoghq.com/nginx.init_configs: '[{}]'
        service-discovery.datadoghq.com/nginx.instances: '[{"nginx_status_url": "http://%%host%%/basic_status", "tags": ["%%tags%%"]}]'
    spec:
      containers:
      - name: nginx
        image: hkaj/nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
